# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HassCli < Formula
  desc "CLI for Home Assistant — query and control your smart home from the terminal or AI agents."
  homepage "https://github.com/ykamakazi/hass-cli"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ykamakazi/hass-cli/releases/download/v0.1.6/hass_0.1.6_darwin_amd64.tar.gz"
      sha256 "6262fd444ad085f1cbb249616ba58756a272a68b8b36af0cd95962ebf81c9631"

      define_method(:install) do
        bin.install "hass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ykamakazi/hass-cli/releases/download/v0.1.6/hass_0.1.6_darwin_arm64.tar.gz"
      sha256 "783ba94297ca5d447342cfa63ac24aaecf69c42313b2483ad0827d9b1db3beba"

      define_method(:install) do
        bin.install "hass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ykamakazi/hass-cli/releases/download/v0.1.6/hass_0.1.6_linux_amd64.tar.gz"
      sha256 "21a230ee774c992aef9e57ca6e07ec86cc66640e7b9481637a7e283e5073f800"
      define_method(:install) do
        bin.install "hass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ykamakazi/hass-cli/releases/download/v0.1.6/hass_0.1.6_linux_arm64.tar.gz"
      sha256 "dd49d6929605b81e70c5e17f02bd772c9aeb4252ebeb4df42b4ce216cdf24d88"
      define_method(:install) do
        bin.install "hass"
      end
    end
  end

  test do
    system "#{bin}/hass", "version"
  end
end
